version: "3"

services:
  app:
    working_dir: /app
    container_name: node-template
    build: .
    command: ["./wait-for-it.sh", "--timeout=0", "mysql:3306", "--", "npm", "run", "prod"]
    ports:
      - 3000:3000
    links:
      - mysql
    volumes:
      - ./:/app
    depends_on:
      - mysql
  mysql:
    container_name: node-template-mysql
    image: mysql:5.7.25
    ports:
        - "3306:3306"
    volumes:
        - ./sql:/docker-entrypoint-initdb.d/
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: root
